<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CK.DB.AspNet.Auth" Version="31.0.3--ci.6" />
    <PackageReference Include="CK.DB.User.UserOidc" Version="28.0.3--ci.1" />
    <PackageReference Include="CK.DB.User.UserPassword" Version="28.0.3--ci.6" />
  </ItemGroup>
</Project>